runner-core/src/test/java/org/apache/apisix/plugin/runner/codec/impl/FlatBuffersEncoderTest.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/HttpResponse.java

fix the bug of setting multiple headers and args

fix: set more headers and args

---

CHANGELOG.md

___
- Description
Fix symbol errors in changelog.
- How to fix?
Change incorrect symbol.

fix: changelog markdown typo

---

docs/en/latest/how-it-works.md

___
- Description
- How to fix?
___

docs: fix the dist package name

---

pom.xml

___
- Description
- How to fix?
___

chore: upgrade log4j2 version to 2.15.0

---

docs/zh/Quick Start.md

___
- Description
- How to fix?
___
- add zh Qucik start doc

docs: add zh Quick Start

---

NOTICE
runner-dist/apisix-runner-bin-dist/src/main/release-docs/NOTICE

___
- Description
- How to fix?
___

chore: update copyright to 2022

---

README.md
docs/en/latest/development.md
docs/zh/quick-start.md

Closes #118
___
- Description
- How to fix?
___

chore: adjust the matching APISIX version to 2.12.0

---

runner-core/src/main/java/org/apache/apisix/plugin/runner/handler/HTTPReqCallHandler.java
runner-core/src/test/java/org/apache/apisix/plugin/runner/handler/A6HttpCallHandlerTest.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/HttpRequest.java

Signed-off-by: 123liubao <chenly_61@163.com>
#92 
___
- Description
- How to fix?
___

refactor: rename the name of the function that gets all the headers to 'getHeaders'.

---

.github/workflows/ci.yaml
.github/workflows/runner-e2e.yml
pom.xml

___
- Description
- How to fix?
___

chore: upgrade spring boot release version

---

MAINTAIN.md

Description: 
Details the steps to deploying apisix-java-plugin-runner to Maven.

docs: add MAINTAIN.md

---

docs/en/latest/development.md
runner-core/src/main/java/org/apache/apisix/plugin/runner/constants/Constants.java
runner-core/src/main/java/org/apache/apisix/plugin/runner/handler/PayloadDecoder.java
runner-core/src/main/java/org/apache/apisix/plugin/runner/handler/RpcCallHandler.java
runner-core/src/main/java/org/apache/apisix/plugin/runner/server/ApplicationRunner.java
runner-core/src/test/java/org/apache/apisix/plugin/runner/handler/A6HttpCallHandlerTest.java
runner-core/src/test/java/org/apache/apisix/plugin/runner/handler/ExtraInfoTest.java
runner-core/src/test/java/org/apache/apisix/plugin/runner/handler/PostFilterTest.java
runner-plugin-sdk/pom.xml
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/HttpResponse.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/PostRequest.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/PostResponse.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/filter/PluginFilter.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/filter/PluginFilterChain.java
sample/src/main/java/org/apache/apisix/plugin/runner/filter/ResponseFilter.java
src/main/checkstyle/checkstyle-suppressions.xml
tests/e2e/plugins/plugins_post_test.go

Closes #102
- Related issues #102 #50
___
- Description
- How to fix?
___

feat: support filter upstream responses

---

docs/en/latest/hot-reloading.md

Provides documentation for new hot reload feature
Related to [PR ](https://github.com/apache/apisix-java-plugin-runner/pull/158)

docs: add hot-reloading documentation

---

CHANGELOG.md
Makefile
pom.xml
runner-core/pom.xml
runner-dist/apisix-runner-bin-dist/pom.xml
runner-dist/apisix-runner-src-dist/pom.xml
runner-dist/pom.xml
runner-plugin-sdk/pom.xml
runner-plugin/pom.xml
runner-starter/pom.xml
sample/pom.xml

___
- Description
- How to fix?
___

feat: release 0.3.0

---

MAINTAIN.md
Makefile

___
- Description
- How to fix?
___

docs: update MAINTAIN.md

---

Makefile

#190
___
- Description
- How to fix?
___

chore: fix missing parent project on deploy

---

docs/en/latest/installation-guide.md
pom.xml
runner-core/pom.xml
runner-dist/apisix-runner-bin-dist/pom.xml
runner-dist/apisix-runner-src-dist/pom.xml
runner-dist/pom.xml
runner-plugin-sdk/pom.xml
runner-plugin/pom.xml
runner-starter/pom.xml
sample/pom.xml

___
- Description
- How to fix?
___

feat: update version to 0.3.1-SNAPSHOT

---

ci/apisix/config.yaml
ci/docker-compose.yml
docs/en/latest/development.md
docs/en/latest/installation-guide.md
runner-core/src/main/java/org/apache/apisix/plugin/runner/handler/RpcCallHandler.java
runner-plugin-sdk/pom.xml
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/ExtraInfoRequest.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/PostRequest.java
runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/filter/PluginFilter.java
sample/src/main/java/org/apache/apisix/plugin/runner/filter/PostReqWithVarsFilter.java
tests/e2e/plugins/plugins_post_with_vars_test.go

___
- Description
- How to fix?
___

feat: support for getting upstream response body

---

docs/zh/quick-start.md

* The quick start document is out of date. For example : the PluginFilter's signature and jre version.
*  Add a guide to remote debug with Java plugin in docker.

docs: improve quick start document

---

CHANGELOG.md
Makefile
README.md
docs/en/latest/installation-guide.md
pom.xml
runner-core/pom.xml
runner-dist/apisix-runner-bin-dist/pom.xml
runner-dist/apisix-runner-src-dist/pom.xml
runner-dist/pom.xml
runner-plugin-sdk/pom.xml
runner-plugin/pom.xml
runner-starter/pom.xml
sample/pom.xml

___
- Description
- How to fix?
___

feat: release 0.4.0

---

CHANGELOG.md
Makefile
README.md
docs/en/latest/installation-guide.md
pom.xml
runner-core/pom.xml
runner-dist/apisix-runner-bin-dist/pom.xml
runner-dist/apisix-runner-src-dist/pom.xml
runner-dist/pom.xml
runner-plugin-sdk/pom.xml
runner-plugin/pom.xml
runner-starter/pom.xml
sample/pom.xml

feat: release 0.5.0

---

docs/en/latest/installation-guide.md

- Related issues #303 
___
- Description
Development doc's location was updated, hence we need to update the link.
- How to fix?
Update its link.
___

docs: update development doc link in installation-guide.md

---

.github/workflows/ci.yaml
.github/workflows/runner-e2e.yml
docs/en/latest/installation-guide.md
docs/zh/quick-start.md
pom.xml

- Related issues https://github.com/apache/apisix-java-plugin-runner/issues/314
4 year outdated dependencies on a component loaded at the edge of ones network... Let's remediate that!

ISSUE-314 Upgrade dependencies & adopt Java 21

---

README.md

___
- Description
- How to fix?
___

doc: add tips

---

CHANGELOG.md
Makefile
README.md
docs/en/latest/installation-guide.md
pom.xml
runner-core/pom.xml
runner-dist/apisix-runner-bin-dist/pom.xml
runner-dist/apisix-runner-src-dist/pom.xml
runner-dist/pom.xml
runner-plugin-sdk/pom.xml
runner-plugin/pom.xml
runner-starter/pom.xml
sample/pom.xml

___
- Description
- How to fix?
___

release: 0.6.0
